language: python
env:
    - NENGINES=1
    - NENGINES=9
python:
    - 2.7
    - 3.3
    - 3.4
before_install:
    - sudo apt-get update
    - sudo apt-get install libopenmpi-dev
    - sudo apt-get install openmpi-bin
    - sudo apt-get install libhdf5-openmpi-dev
    - pip install numpy
    - pip install pyzmq --install-option="--zmq=bundled"
    - pip install ipython
    - pip install matplotlib  # for plotting.py
    - pip install mpi4py --allow-all-external --allow-unverified mpi4py
    - pip install cython
    - CC=mpicc pip install git+https://github.com/h5py/h5py.git@2.2.1 --install-option="--mpi"
    - pip install sphinx
    - pip install sphinxcontrib-napoleon
    - pip install coverage
    - pip install coveralls
    - pip freeze
install:
    - python setup.py install
    - (cd $TRAVIS_BUILD_DIR && cd docs && make html)
before_script:
    - "export DISPLAY=:99.0"  # for plotting.py
    - "sh -e /etc/init.d/xvfb start"  # for plotting.py
    - (cd $TRAVIS_BUILD_DIR && dacluster start -n$NENGINES)
    - lsof | grep python | wc -l
script:
    - (cd $TRAVIS_BUILD_DIR && make test_with_coverage)
after_script:
    - lsof | grep python | wc -l
    - (cd $TRAVIS_BUILD_DIR && dacluster stop)
after_success:
    - coverage combine
    - coveralls
